"""MJLab velocity task registrations."""

from . import (  # noqa: F401
    agibot_d1,
    anybotics_anymal_d,
    booster_t1,
    ddtrobot_tita,
    deeprobotics_m20,
    deeprobotics_lite3,
    dr02,
    dr02_pro,
    fftai_gr1,
    magiclab_magicdog,
    magiclab_magicdogw,
    magiclab_magicbot,
    openloong_loong,
    roboparty_atom01,
    robotera_xbot,
    unitree_a1,
    unitree_a1_handstand,
    unitree_b2,
    unitree_g1,
    unitree_go2,
    unitree_h1,
    unitree_b2w,
    unitree_go2w,
    zsibot_zsl1,
    zsibot_zsl1w,
)
